music_directory		"~/Music/Library"
playlist_directory	"~/.config/mpd/playlists"
db_file			"~/.local/share/mpd/database"
state_file		"~/.local/share/mpd/state"
sticker_file		"~/.local/share/mpd/sticker.sql"

bind_to_address		"/run/user/1000/mpd/socket"

auto_update		"yes"

audio_output {
	type		"pipewire"
	name		"PipeWire Output"
}
