set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"


set -g mouse on 

# options
## keymaps
#unbind C-b
#set-option -g prefix C-space
#bind-key C-space send-prefix

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
#set -g @plugin 'alexwforsythe/tmux-which-key'
#set -g @plugin 'tmux-plugins/tmux-pain-control' #homerow pane controls (not arrows)

set -g @plugin '2kabhishek/tmux2k'
set -g @tmux2k-theme 'default'
set -g @tmux2k-show-powerline false
set -g @tmux2k-icons-only true
set -g @tmux2k-left-plugins "session"


set -g @plugin 'whame/tmux-modal'
set -g @modal-keybindings-conf ~/.config/tmux/my-tmux-modal-keybindings.conf

#tmux sessionx
set -g @plugin 'omerxx/tmux-sessionx'
set -g @sessionx-bind 'o'


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# for (yazi) image preview
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
