general {
    lock_cmd = pidof swaylock || swaylock
    before_sleep_cmd = swaylock
    ignore_dbus_inhibit = false
}

listener {
    timeout = 300
    on-timeout = swaylock
}

listener {
    timeout = 600
    on-timeout = wlopm --off '*' && systemctl --user stop wallpaper-playlist.timer
    on-resume = wlopm --on '*' && systemctl --user start wallpaper-playlist.timer
}
