general {
    lock_cmd = pidof swaylock || swaylock
    before_sleep_cmd = swaylock
    ignore_dbus_inhibit = false
}

listener {
    timeout = 300
    on-timeout = swaylock
}

listener {
    timeout = 600
    on-timeout = wlopm --off DP-2; wlopm --off '*'; systemctl --user stop wallpaper-playlist.timer; bluetoothctl disconnect $(bluetoothctl devices | grep 'MX Master 3S' | awk '{print $2}')
    on-resume = wlopm --on DP-2; wlopm --on '*'; systemctl --user start wallpaper-playlist.timer; bluetoothctl connect $(bluetoothctl devices | grep 'MX Master 3S' | awk '{print $2}')
}
