;;; vv-org-tags.el --- Org tag hierarchy

(setq org-tag-alist
      '(;; groups
        (:startgrouptag)
        ("work")
        (:grouptags)
        ("BcSCS")
        ("musicwork")
        (:endgrouptag)

        (:startgrouptag)
        ("BcSCS")
        (:grouptags)
        ("S1")
        ("S2")
        ("S3")
        (:endgrouptag)

        (:startgrouptag)
        ("S1")
        (:grouptags)
        ("1_1W")
        ("1_2T")
        ("1_3M")
        (:endgrouptag)

        (:startgrouptag)
        ("S2")
        (:grouptags)
        ("2_1W" . ?W)
        ("2_2T")
        (:endgrouptag)

        (:startgrouptag)
        ("musicwork")
        (:grouptags)
        ("DJing")
        ("production")
        ("st". ?s)
        ("CC". ?c)
        ("HSA". ?h)
        ("idElectro". ?e)
        ("idTrap". ?d)
        ("idLDnB". ?l)
        (:endgrouptag)

        (:startgrouptag)
        ("DJing")
        (:grouptags)
        ("library")
        ("DJgear")
        (:endgrouptag)

        (:startgrouptag)
        ("library")
        (:grouptags)
        ("recdigging". ?d)
        ("recgetting")
        (:endgrouptag)

        (:startgrouptag)
        ("recgetting")
        (:grouptags)
        ("IDs" . ?i)
        ("tracks" . ?t)
        (:endgrouptag)

        (:startgrouptag)
        ("DJgear")
        (:grouptags)
        ("viv2")
        ("model1")
        (:endgrouptag)

        (:startgrouptag)
        ("personal")
        (:grouptags)
        ("productivity")
        ("health")
        (:endgrouptag)

        (:startgrouptag)
        ("health")
        (:grouptags)
        ("mentalhealth")
        (:endgrouptag)

        (:startgrouptag)
        ("hometime")
        (:grouptags)
        ("watch")
        (:endgrouptag)

        (:startgrouptag)
        ("chores")
        (:grouptags)
        ("digichores")
        ("domestic")
        (:endgrouptag)

        (:startgrouptag)
        ("digichores")
        (:grouptags)
        ("ricefields")
        (:endgrouptag)

        (:startgrouptag)
        ("ricefields")
        (:grouptags)
        ("neovim")
        ("orgmode")
        ("keymappings")
        (:endgrouptag)

        (:startgrouptag)
        ("shopping")
        (:grouptags)
        ("groceries")
        ("living")
        (:endgrouptag)

        (:startgrouptag)
        ("locations")
        (:grouptags)
        ("berlin")
        ("stuttgart")
        ("fhafen")
        (:endgrouptag)))

(provide 'vv-org-tags)
