;;; vv-org-tags.el --- Org tag hierarchy

(setq org-tag-alist
      '(;; groups
        (:startgrouptag)
        ("work")
        (:grouptags)
        ("computerwork")
        ("musicwork")
        (:endgrouptag)

        (:startgrouptag)
        ("computerwork")
        (:grouptags)
        ("uni")
        (:endgrouptag)

        (:startgrouptag)
        ("uni")
        (:grouptags)
        ("BcSCS")
        ("42")
        (:endgrouptag)

        (:startgrouptag)
        ("BcSCS")
        (:grouptags)
        ("S1")
        ("S2")
        ("S3")
        (:endgrouptag)

        (:startgrouptag)
        ("42")
        (:grouptags)
        ("curriculum")
        (:endgrouptag)

        (:startgrouptag)
        ("curriculum")
        (:grouptags)
        ("commoncore")
        (:endgrouptag)

        (:startgrouptag)
        ("commoncore")
        (:grouptags)
        ("rank00")
        ("rank01")
        ("rank02")
        ("rank03")
        ("rank04")
        ("rank05")
        ("rank06")
        (:endgrouptag)

        (:startgrouptag)
        ("rank01")
        (:grouptags)
        ("born2beroot")
        (:endgrouptag)

        (:startgrouptag)
        ("S1")
        (:grouptags)
        ("1_1W")
        ("1_2T")
        ("1_3M")
        (:endgrouptag)

        (:startgrouptag)
        ("S2")
        (:grouptags)
        ("2_1W")
        ("2_2T")
        (:endgrouptag)

        (:startgrouptag)
        ("musicwork")
        (:grouptags)
        ("DJing")
        ("production")
        ("st". ?s)
        ("CC". ?c)
        ("HSA". ?h)
        ("idElectro". ?e)
        ("idTrap". ?d)
        ("idLDnB". ?l)
        (:endgrouptag)

        (:startgrouptag)
        ("DJing")
        (:grouptags)
		("tracks")
        ("library")
        ("DJgear")
        (:endgrouptag)

        (:startgrouptag)
        ("tracks")
        (:grouptags)
		("dig")
		("get")
		("ID")
        ("recdigging")
        ("recgetting")
        (:endgrouptag)

        (:startgrouptag)
        ("recgetting")
        (:grouptags)
        ("IDs")
        ("tracks")
        (:endgrouptag)

        (:startgrouptag)
        ("DJgear")
        (:grouptags)
        ("viv2")
        ("model1")
        (:endgrouptag)

        (:startgrouptag)
        ("personal")
        (:grouptags)
        ("productivity")
        ("health")
        (:endgrouptag)

        (:startgrouptag)
        ("health")
        (:grouptags)
        ("mentalhealth")
        (:endgrouptag)

        (:startgrouptag)
        ("watch")
        (:grouptags)
        ("movie")
        ("series")
        (:endgrouptag)

        (:startgrouptag)
        ("chores")
        (:grouptags)
        ("domestic")
        (:endgrouptag)


        (:startgrouptag)
        ("ricefields")
        (:grouptags)
        ("neovim")
        ("orgmode")
        ("org")
        ("keymappings")
        ("keymaps")
        (:endgrouptag)

        (:startgrouptag)
        ("shopping")
        (:grouptags)
        ("groceries")
        ("living")
        (:endgrouptag)

        (:startgrouptag)
        ("locations")
        (:grouptags)
        ("city")
        ("home")
        (:endgrouptag)

        (:startgrouptag)
        ("city")
        (:grouptags)
        ("berlin")
        ("stuttgart")
        ("fhafen")
        (:endgrouptag)))

(provide 'vv-org-tags)
