keymode=open_mode
bind=SUPER,1,spawn,mmsg-vv mode switch default
bind=NONE,Escape,spawn,mmsg-vv mode switch normal_mode
bind=NONE,m,spawn,mmsg-vv mode switch open_message_mode
bind=NONE,c,spawn,mmsg-vv mode switch open_config_mode
bind=NONE,o,spawn,mmsg-vv mode switch org_open_mode
bind=NONE,f,spawn,foot
bind=NONE,s,spawn,glide
bind=NONE,space,spawn_shell,mmsg-vv dispatch-and-switch 'spawn_shell,j4-dmenu-desktop --dmenu="bemenu -c -i -W 0.2 -l 15"' default
bind=SHIFT,space,spawn_shell,mmsg-vv dispatch-and-switch 'spawn_shell,bemenu-run -i -c -W 0.2 -l 15' default
bind=NONE,n,view,6
bind=NONE,n,spawn_shell,mmsg-vv dispatch-and-switch 'toggle_named_scratchpad,pomoterm,none,qutebrowser --desktop-file-name "keybrbrowser" --target window https://www.keybr.com/' default


keymode=org_open_mode
bind=SUPER,1,spawn,mmsg-vv mode switch default
bind=NONE,Escape,spawn,mmsg-vv mode switch normal_mode
bind=NONE,a,spawn_shell,mmsg-vv dispatch-and-switch "spawn_shell,nu --no-std-lib ~/.config/mango/em.nu org agenda list" default
bind=NONE,o,spawn_shell,mmsg-vv dispatch-and-switch "spawn_shell,nu --no-std-lib ~/.config/mango/em.nu org agenda" default
bind=NONE,t,spawn_shell,mmsg-vv dispatch-and-switch "spawn_shell,nu --no-std-lib ~/.config/mango/em.nu org roam dailies today goto" default
bind=NONE,s,spawn_shell,mmsg-vv dispatch-and-switch "spawn_shell,nu --no-std-lib ~/.config/mango/em.nu emacs scratch" default


keymode=open_message_mode
bind=SUPER,1,spawn,mmsg-vv mode switch default
bind=NONE,m,view,8,0
bind=NONE,m,spawn_shell,mmsg-vv dispatch-and-switch 'spawn,foot iamb' default
bind=NONE,d,view,8,0
bind=NONE,d,spawn_shell,mmsg-vv dispatch-and-switch 'spawn,Discord' default
bind=NONE,j,view,8,0
bind=NONE,j,spawn_shell,mmsg-vv dispatch-and-switch 'spawn,gajim' default
bind=NONE,t,view,8,0
bind=NONE,t,spawn_shell,mmsg-vv dispatch-and-switch 'spawn_shell,flatpak run org.telegram.desktop' default
bind=NONE,s,view,8,0
bind=NONE,s,spawn_shell,mmsg-vv dispatch-and-switch 'spawn_shell,flatpak run org.signal.Signal' default

keymode=open_config_mode
bind=SUPER,1,spawn,mmsg-vv mode switch default
bind=NONE,Escape,spawn,mmsg-vv mode switch normal_mode
