[language-server.fennel-ls]
command = "fennel-ls"

[[language]]
name = "fennel"
scope = "source.fennel"
file-types = ["fnl"]
language-servers = ["fennel-ls"]
formatter = { command = "fnlfmt", args = ["-"]}

[[grammar]]
name = "fennel"
source.git = "https://github.com/alexmozaidze/tree-sitter-fennel"
source.rev = "ea4a536bca8997e30b22709f210f44f97e75bf7d"


